import { Inter, Manrope, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-manrope",
});
const beVietNamePro = Be_Vietnam_Pro({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-be_vietname_pro",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${manrope.variable} ${beVietNamePro.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
